# http://192.168.2.126:30007/
apiVersion: v1
kind: Service
metadata:
  name: brother-dcpj152-cups-service
spec:
  selector:
    app: brother-dcpj152-cups
  type: NodePort
  ports:
  - port: 631
    targetPort: 631
    nodePort: 30007 # keep NodePort because of current printer setup
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: brother-dcpj152-cups-service-clusterip
spec:
  selector:
    app: brother-dcpj152-cups
  type: ClusterIP
  ports:
  - port: 631
    targetPort: 631

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: brother-dcpj152-cups
  annotations:
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/whitelist-source-range:  192.168.2.0/24
    nginx.ingress.kubernetes.io/upstream-vhost: "192.168.2.126" # ip of node :-(
spec:
  rules:
  - host: print.h5b.de
    http:
      paths:
      - path: /
        backend:
          serviceName: brother-dcpj152-cups-service-clusterip
          servicePort: 631